/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { assert, it } from "vitest";

it.skip("User Addcredential", async () => {
  assert.fail(
    "incomplete test found please make sure to address the following errors: [`workflow step addcredential.test referencing operation addcredential not found in document`]",
  );
});

it.skip("User Deletequeryhistory", async () => {
  assert.fail(
    "incomplete test found please make sure to address the following errors: [`workflow step deletequeryhistory.test referencing operation deletequeryhistory not found in document`]",
  );
});

it.skip("User Invite", async () => {
  assert.fail(
    "incomplete test found please make sure to address the following errors: [`workflow step invite.test referencing operation invite not found in document`]",
  );
});

it.skip("User Publicconfig", async () => {
  assert.fail(
    "incomplete test found please make sure to address the following errors: [`workflow step publicconfig.test referencing operation publicconfig not found in document`]",
  );
});

it.skip("User Removecredential", async () => {
  assert.fail(
    "incomplete test found please make sure to address the following errors: [`workflow step removecredential.test referencing operation removecredential not found in document`]",
  );
});

it.skip("User Support Email", async () => {
  assert.fail(
    "incomplete test found please make sure to address the following errors: [`workflow step support_email.test referencing operation support_email not found in document`]",
  );
});
